### ISSUE TITLE
Adding additional detector data to lcsim

### ISSUE THREAD

**Issue by chekanov** [slaclab/lcsim#2]
Hello, Jeremy

 This is more a suggestion, than a bug, therefore, we have agreed with David that I'll put it here. Many detectors implemented in HepSim are located in this URL link:

 http://atlaswww.hep.anl.gov/hepsim/soft/detectors/taglist.txt

 therefore, I had to change

 MASTER_TAGLIST_URL = "http://lcsim.org/detectors/taglist.txt"; 

to

  MASTER_TAGLIST_URL = "http://atlaswww.hep.anl.gov/hepsim/soft/detectors/taglist.txt"; 

inside 

./detector-framework/src/main/java/org/lcsim/geometry/util/DetectorLocator.java

Is it possible to read this URL via an external configuration file?

best, Sergei

**Comment by JeremyMcCormick** [comment]
@chekanov 

We have moved towards packaging all the detectors in the jar file and accessing them as class resources.  This makes downloading them from a remote URL unnecessary.  However, it would require making your project depend on rather than use lcsim so that you could bundle the extra detector data.  Is this an acceptable solution?
